{% set name = "wurlitzer" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01cb41f3bccc339632a28cb147b622241e785c23e11c69ce08efad5ebd2c427f

build:
  skip: true  # [win]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - selectors2  # [py==27]

test:
  imports:
    - wurlitzer
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/minrk/wurlitzer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Capture C-level stdout/stderr in Python'
  dev_url: https://github.com/minrk/wurlitzer
  doc_url: https://github.com/minrk/wurlitzer/blob/main/README.md

extra:
  recipe-maintainers:
    - minrk
    - bjodah
    - asmeurer
