travis:
  secure:
    BINSTAR_TOKEN: IKE6DCJU4dpDSTfeFautOYI5ziU/l4c4eyJkSXsn2foKg2f5sYc2+O2q6hlhL52JZ+RCrwNGnhzKLOkjh20N4Bd+gbj6PB6sIBDjuDnpfD1YUhUP7pKL8i43wmKoLyzqEBXetfFJ7ICr7hRV8GZRWol9myJQA1/1xaSMx66Z8vgULoYslDKIl2mec4R36Yf7ZplHDMHNt27HV3OaSUIfeWGPz89H1eGbmC+/J4OrhW1r/HvRGjMCHYcnwiSmZHp+piODJzfoyS+MdCGXlEcM6hYRN/+IQiYVC3X9hLg9oZdNqGu0EettDCkuArrV2wsXEGuGll+99Cy7A9clR1DN5YR9pSuE5XNbaYXniOtXn8tUXYVMCXIcMxmhQzIlY/GbR7fp3Mb1hHRdiOBdPTornAOrw0lybqD1nfZcE+sD3WU/gM2eiWUWODXypuNz+nmDXVJ08FbElpNeHgPZIyRyjdvP5uH0Py0+hVLKjXgzgP/ASd6MtAYdsRcP5R35tw5f+/G7AByuAEregQfftxKNjRDOeG2kAp6axay3rzJ6cuzQNjvnK6UOMASB5QPABf8YuWM3jUsMPFCHta7UW+V1Bprm42vSk4qaxoigEW0iKhyVMh6mvvtTBiwX83Y130b9FzrPKZvKTfvju/1/0XrhR7xUXpfeKxQEEPIZqBdTJhE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
